name: TokumeiPlugin
version: 0.0.1
main: sanpe.plugin.tokumeiplugin.TokumeiPlugin
commands:
   tokumei:
      description: チャットを匿名化
      usage: "Usage: /tokumei [start|stop]"
      permission: tokumeiplugin.tokumei
      permission-message: You don't have <permission>